# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2872969bcae83348c44e8bd91545c18e6fda04eba857fcd3dc0d3dc8edb7fa0d8cfce99d7eef9a81d0e061823d59b42ac4e5a8447ff66066b71367678480e5db

test:
  secret_key_base: cdc90be98019cb3945b4b340feba817488dfb14d866180e053d122680593c154149ad1b437a8d523b84e457a7b8384b87030cfd72eda5b64e6576cefcea19b58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
